[pytest]
DJANGO_SETTINGS_MODULE = webcrm.settings
python_files = test_*.py
testpaths = tests
addopts = --alluredir=allure-results
filterwarnings =
    ignore::pytest.PytestUnhandledThreadExceptionWarning
